pretrained_weights: Null

embed_dim: 256
ffn_dim: 2048
num_heads: 8
num_deformable_heads: 16
num_points: 2
dropout: 0.1
num_groups: 13
num_queries: 300
num_denoise_queries: 300
pos_noise_scale: 0.4
neg_noise_scale: 0.8
label_noise_prob: 0.25

backbone:
  embed_dim: ${model.embed_dim}
  feature_extractor:
    name: facebook/dinov2-with-registers-small
    image_size: ${transforms.val.resolution}
    patch_size: 16
    out_feature_indices: [2, 5, 8, 11]
    window_layer_indices: [0, 1, 3, 4, 6, 7, 9, 10]
    num_windows: 2
  projector:
    embed_dim: ${model.embed_dim}
    multi_scale: True
    out_strides: [16]
    num_blocks: 3
  pretrained: True

encoder:
  num_layers: 0
  embed_dim: ${model.embed_dim}
  layer:
    _target_: models.layers.encoder.DeformableEncoderLayer
    embed_dim: ${model.embed_dim}
    ffn_dim: ${model.ffn_dim}
    num_heads: ${model.num_deformable_heads}
    num_points: ${model.num_points}
    dropout: ${model.dropout}

decoder:
  num_layers: 4
  two_stage: True
  refine_boxes: False 
  denoise_queries: True
  num_groups: ${model.num_groups}
  num_queries: ${model.num_queries}
  num_denoise_queries: ${model.num_denoise_queries} 
  embed_dim: ${model.embed_dim}
  pos_noise_scale: ${model.pos_noise_scale}
  neg_noise_scale: ${model.neg_noise_scale}
  label_noise_prob: ${model.label_noise_prob}
  layer:
    _target_: models.layers.decoder.DeformableDecoderLayer
    embed_dim: ${model.embed_dim}
    ffn_dim: ${model.ffn_dim}
    num_heads: ${model.num_heads}
    num_deformable_heads: ${model.num_deformable_heads}
    num_points: ${model.num_points}
    dropout: ${model.dropout}
