defaults:
  - hydra: logging
  - dataset: coco
  - transforms: small
  - model: small
  - optimizer: adamw
  - scheduler: step
  - criterion: set
  - ema: warmup
  - _self_

train:
  output_dir: /path/to/output/dir
  num_epochs: 24
  num_warmup_epochs: 2
  num_cooldown_epochs: 12
  num_finetune_epochs: 2
  batch_size: 16
  num_workers: 4
  save_period: 1
  max_grad_norm: 0.1
  grad_accum_steps: 1
  random_seed: 42
  enable_wandb: True
  checkpoint: Null
